### ISSUE TITLE
Questionnaire integration

### ISSUE THREAD

**Issue by arunge** [Pandora-IsoMemo/MapR#13]
- [x] Users can fill in a questionnaire (either multiple choice questions or text inputs) and depending on their inputs a certain figure will be displayed on MapR’s interface.
- [x] A JSON file instance will contain all information on questionnaire and which figures to be displayed. Depending on loaded JSON file the interface will adapt accordingly to display the relevant elements (e.g., radio buttons for multiple choice questions or text inputs boxes). The JSON file also describes the location of figures in similar manner to what is already implemented.
- [x] Users load the JSON file and the questionnaire starts. One question at a time (either multiple choice or text inputs as mentioned above).
- [x] Once the questionnaire is completed by the user an evaluation of the replies is made to chose which figure to display. The JSON file will thus also contain logical instructions to make figure choice. An example:
  - A questionnaire with two multiple choice questions. In question 1 (Q1), users have to choose between option A or option B. While in question 2 (Q2), users have to enter a number.
  - Logic rules do display one of the four available figures (figure 1, figure 2, figure 3, figure 4)
  - If for Q1 option A is chosen and for Q2 entered number is > 5 then display figure 1
  - If for Q1 option A is chosen and for Q2 entered number is <= 5 then display figure 2
  - If for Q1 option B is chosen and for Q2 entered number is > 5 then display figure 1
  - If for Q1 option B is chosen and for Q2 entered number is <= 5 then display figure 2

The JSON file would have fields for each question on the form of input and text options (e.g., if radio buttons texts for each, if input box the label). The loading of this file can be done using the Pandora interface.

The user loads/runs the file, answers the  questions and the package evaluates the answers. This coud be done by using something like a cases function (from memisc package). Example:

z1=cases(
    "Image 1"=x<0,
    "Image 2"=y<0,# only applies if x >= 0
    "Image 3"=TRUE
    )

The conditions listed above would match each of the questions and define which image to be shown. 

The location of the images follows the same structure as is already implemented. This should not be altered. We are just addition new options to the current JSON structure that allow users to now select images from a questionnaire.

@f-lukas Please feel free to create sub issues as needed!

**Comment by f-lukas** [comment]
@isomemo - The questionnaire is ready for testing here: https://pandoraapp.earth/app/mapr
The easiest way to test the feature is to select an online zip file e.g. `example_data_questionnaire`.
Please refer to the documentation about additional information: https://pandora-isomemo.github.io/MapR/

**Comment by isomemo** [comment]
@f-lukas @arunge I tried to load the example that you mentioned for testing but the import module displays an error:

![image](https://github.com/Pandora-IsoMemo/MapR/assets/46485054/75ff7135-a7e3-4b7c-99da-5c7a5547ff4d)

**Comment by arunge** [comment]
This must be a new issue, possibly from the most recent version. I will check this.

**Comment by arunge** [comment]
@isomemo The fix for the online example in [MapR](https://pandoraapp.earth/app/mapr-beta) is now online and you can start testing the questionaire example. :slightly_smiling_face: 

![image](https://github.com/Pandora-IsoMemo/MapR/assets/16759098/f96de040-8095-4203-9fe8-6feeee13e26a)

**Comment by isomemo** [comment]
@f-lukas @arunge 

![image](https://github.com/user-attachments/assets/2f276438-6046-47d0-b12e-b133dedd9fc7)

Change "Import ZIP file" to "Load MapR file"
Change "Group name" to "Main selection"
Change "Measure" to "Parameter"

There seems to be too much blank space between the displayed graph and the upper and left parts of the display interface.

Are time plots working or not applicable to selected examples?
Please confirm that NTCDF files are working on MapR.

File extensions should be mapr and not zipm

I tried the "example_data_questionnaire" file but when selecting option B got the error "No plot matches the criteria"

**Comment by arunge** [comment]
@f-lukas Today we discussed following renaming:
> Change "Group name" to "Main selection"
> Change "Measure" to "Parameter"

Please, only rename the names in the user interface (not in the code or the json files).
The idea was to simply add a comment into the json file, that
- "Group name" refers to the "Main selection" and 
- "Measure" refers to "Parameter"

However, `.json` does not support comments. Let's shortly discuss how to solve this with little effort, e.g.
- adding a short README into the `mapr` zip file
- switching to e.g. `yaml` files

**Comment by f-lukas** [comment]
@isomemo & @arunge - The following changes are now deployed to the beta and main app:

> Change "Import ZIP file" to "Load MapR file"
> Change "Group name" to "Main selection"
> Change "Measure" to "Parameter"

This was changed in the user interface. Withtin the json file the old names "Group name" and "Measure" are still used. A README was added to the example zip files with an explanation of the names used in the json.

> There seems to be too much blank space between the displayed graph and the upper and left parts of the display interface.

The plot and table is now left aligned. The blank space at the upper part was mainly due to a white frame in the example pngs.

> File extensions should be mapr and not zipm

The file extension was changed to zipm.


Here are also some remarks on the remaining questions:

`Please confirm that NTCDF files are working on MapR.`

NTCDF files are working. Please load the example data and then select the following:
![Bildschirmfoto vom 2024-10-15 09-07-33](https://github.com/user-attachments/assets/82f2d395-a729-4ffd-b0e2-e5701702a8ea)

> Are time plots working or not applicable to selected examples?
Time plots were renamed to Time data and can be selected for all NTCDF files that contain more than one timestamp. 
![Bildschirmfoto vom 2024-10-15 09-09-25](https://github.com/user-attachments/assets/5e9a65f4-9361-43c5-ab51-1cd52650dac0)

> I tried the "example_data_questionnaire" file but when selecting option B got the error "No plot matches the criteria"

The idea of this example was to show a plot with the default values for Option A but to also show what happens if no plot is given for selected values. This is what happens if Option B is selected and the other values are not changed. If you select the following values for Option B, a plot is shown.
![Bildschirmfoto vom 2024-10-15 09-15-11](https://github.com/user-attachments/assets/f300cd20-0767-4962-8bf7-d2625b4f33c8)
This is a really basic example as we did not know how a more meaningful example could look like. We can definetly change this if you want. If you want to, you could create an example questionnaire that follows the structure of this file: https://github.com/Pandora-IsoMemo/MapR/blob/main/inst/app/exampleZip/example_data_questionnaire.mapr

**Comment by arunge** [comment]
@isomemo As mentioned today requests from [above](https://github.com/Pandora-IsoMemo/MapR/issues/13#issuecomment-2325959480) were implemented and questions answered by @f-lukas. I am closing here. 
Please, feel free to re-open in case of more issues or questions!

I also found the document where I read the task regarding adding points etc. Actually, it is already a ticket on github containing the task description: https://github.com/Pandora-IsoMemo/MapR/issues/1
I will open a new issue where we can discuss open points.
